// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMeterWeb.Data.Context;

#nullable disable

namespace SmartMeterWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104105045_LoginLockUser")]
    partial class LoginLockUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("MeterSeq");

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AddressId"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("HouseNo")
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Arrear", b =>
                {
                    b.Property<long>("ArrearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ArrearId"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("ArrearType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("BillId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaidStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArrearId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Arrears", t =>
                        {
                            t.HasCheckConstraint("CK_Arrear_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_Arrear_PaidStatus", "\"PaidStatus\" IN ('Paid','Unpaid','Partially Paid')");

                            t.HasCheckConstraint("CK_Arrear_Type", "\"ArrearType\" IN ('Overdue','Penalty','Interest')");
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Billing", b =>
                {
                    b.Property<long>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BillId"));

                    b.Property<double>("BaseAmount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("BillingPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BillingPeriodStart")
                        .HasColumnType("date");

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DisconnectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("TaxAmount")
                        .HasColumnType("numeric(18,4)");

                    b.Property<double>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(18,4)")
                        .HasComputedColumnSql("\"BaseAmount\" + \"TaxAmount\"", true);

                    b.Property<double>("TotalUnitsConsumed")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("BillId");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Billings", t =>
                        {
                            t.HasCheckConstraint("CK_Billings_PaidStatus", "\"PaymentStatus\" IN ('Paid','Unpaid','Overdue','Cancelled')");
                        });

                    b.HasData(
                        new
                        {
                            BillId = 1L,
                            BaseAmount = 901.79999999999995,
                            BillingPeriodEnd = new DateOnly(2025, 9, 1),
                            BillingPeriodStart = new DateOnly(2025, 8, 1),
                            ConsumerId = 1L,
                            DueDate = new DateOnly(2025, 9, 15),
                            GeneratedAt = new DateTime(2025, 9, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = "GN24A00187",
                            PaidDate = new DateTime(2025, 9, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = "Paid",
                            TaxAmount = 90.180000000000007,
                            TotalAmount = 0.0,
                            TotalUnitsConsumed = 175.30000000000001
                        },
                        new
                        {
                            BillId = 2L,
                            BaseAmount = 7296.1199999999999,
                            BillingPeriodEnd = new DateOnly(2025, 9, 1),
                            BillingPeriodStart = new DateOnly(2025, 8, 1),
                            ConsumerId = 2L,
                            DueDate = new DateOnly(2025, 9, 15),
                            GeneratedAt = new DateTime(2025, 9, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = "LT24C00255",
                            PaidDate = new DateTime(2025, 9, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = "Paid",
                            TaxAmount = 875.52999999999997,
                            TotalAmount = 0.0,
                            TotalUnitsConsumed = 910.5
                        },
                        new
                        {
                            BillId = 3L,
                            BaseAmount = 1264.2,
                            BillingPeriodEnd = new DateOnly(2025, 9, 1),
                            BillingPeriodStart = new DateOnly(2025, 8, 1),
                            ConsumerId = 3L,
                            DueDate = new DateOnly(2025, 9, 15),
                            GeneratedAt = new DateTime(2025, 9, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = "GN24A00193",
                            PaidDate = new DateTime(2025, 9, 12, 11, 45, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = "Paid",
                            TaxAmount = 126.42,
                            TotalAmount = 0.0,
                            TotalUnitsConsumed = 225.19999999999999
                        },
                        new
                        {
                            BillId = 4L,
                            BaseAmount = 966.75,
                            BillingPeriodEnd = new DateOnly(2025, 9, 1),
                            BillingPeriodStart = new DateOnly(2025, 8, 1),
                            ConsumerId = 4L,
                            DueDate = new DateOnly(2025, 9, 15),
                            GeneratedAt = new DateTime(2025, 9, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = "HP24E00301",
                            PaidDate = new DateTime(2025, 9, 7, 16, 20, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = "Paid",
                            TaxAmount = 77.340000000000003,
                            TotalAmount = 0.0,
                            TotalUnitsConsumed = 154.5
                        },
                        new
                        {
                            BillId = 5L,
                            BaseAmount = 121655.60000000001,
                            BillingPeriodEnd = new DateOnly(2025, 9, 1),
                            BillingPeriodStart = new DateOnly(2025, 8, 1),
                            ConsumerId = 5L,
                            DueDate = new DateOnly(2025, 9, 15),
                            GeneratedAt = new DateTime(2025, 9, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = "LT24I00419",
                            PaidDate = new DateTime(2025, 9, 5, 9, 15, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = "Paid",
                            TaxAmount = 18248.34,
                            TotalAmount = 0.0,
                            TotalUnitsConsumed = 12221.299999999999
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Consumer", b =>
                {
                    b.Property<long>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ConsumerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("ConsumerId");

                    b.HasIndex("Name");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("TariffId");

                    b.ToTable("Consumers", t =>
                        {
                            t.HasCheckConstraint("CK_Consumer_timestamp", "\"UpdatedAt\" IS NULL OR \"UpdatedAt\" > \"CreatedAt\"");
                        });

                    b.HasData(
                        new
                        {
                            ConsumerId = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Email = "priya.s@example.com",
                            IsDeleted = false,
                            Name = "Priya Sharma",
                            OrgUnitId = 5,
                            PasswordHash = "$2a$11$pXHOt/8COqUisMbyPjx7Euy2y3myYS9AukeD6jNo91NtYXmKy.k4W",
                            Phone = "9876543211",
                            Status = "Active",
                            TariffId = 1
                        },
                        new
                        {
                            ConsumerId = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Email = "rohan.k@example.com",
                            IsDeleted = false,
                            Name = "Rohan Kumar",
                            OrgUnitId = 5,
                            PasswordHash = "$2a$11$pXHOt/8COqUisMbyPjx7Euy2y3myYS9AukeD6jNo91NtYXmKy.k4W",
                            Phone = "9876543212",
                            Status = "Active",
                            TariffId = 2
                        },
                        new
                        {
                            ConsumerId = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Email = "vikram.s@example.com",
                            IsDeleted = false,
                            Name = "Vikram Singh",
                            OrgUnitId = 6,
                            PasswordHash = "$2a$11$pXHOt/8COqUisMbyPjx7Euy2y3myYS9AukeD6jNo91NtYXmKy.k4W",
                            Phone = "9876543213",
                            Status = "Active",
                            TariffId = 1
                        },
                        new
                        {
                            ConsumerId = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Email = "anjali.d@example.com",
                            IsDeleted = false,
                            Name = "Anjali Devi",
                            OrgUnitId = 6,
                            PasswordHash = "$2a$11$pXHOt/8COqUisMbyPjx7Euy2y3myYS9AukeD6jNo91NtYXmKy.k4W",
                            Phone = "9876543214",
                            Status = "Active",
                            TariffId = 5
                        },
                        new
                        {
                            ConsumerId = 5L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "System",
                            Email = "contact@guptaindustries.com",
                            IsDeleted = false,
                            Name = "Gupta Industries",
                            OrgUnitId = 5,
                            PasswordHash = "$2a$11$pXHOt/8COqUisMbyPjx7Euy2y3myYS9AukeD6jNo91NtYXmKy.k4W",
                            Phone = "9876543215",
                            Status = "Active",
                            TariffId = 3
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.CustomerCareMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<long>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("CustomerCareMessages");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Meter", b =>
                {
                    b.Property<string>("MeterSerialNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("'SM' || LPAD(nextval('\"MeterSeq\"')::text, 5, '0')");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ICCID")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IMSI")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("InstallTsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MeterSerialNo");

                    b.HasIndex("ConsumerId");

                    b.ToTable("Meters", t =>
                        {
                            t.HasCheckConstraint("CK_Meter_Status", "\"Status\" IN ('Active','Inactive','Decommissioned')");
                        });

                    b.HasData(
                        new
                        {
                            MeterSerialNo = "GN24A00187",
                            Category = "Single Phase",
                            ConsumerId = 1L,
                            Firmware = "v2.1.3",
                            ICCID = "899110234567890123A",
                            IMSI = "404112345678901",
                            InstallTsUtc = new DateTimeOffset(new DateTime(2024, 2, 15, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IpAddress = "192.168.1.101",
                            Manufacturer = "Genus Power",
                            Status = "Active"
                        },
                        new
                        {
                            MeterSerialNo = "LT24C00255",
                            Category = "Three Phase",
                            ConsumerId = 2L,
                            Firmware = "v4.5.1",
                            ICCID = "899110234567890123B",
                            IMSI = "404112345678902",
                            InstallTsUtc = new DateTimeOffset(new DateTime(2024, 3, 20, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IpAddress = "192.168.1.102",
                            Manufacturer = "L&T Electrical",
                            Status = "Active"
                        },
                        new
                        {
                            MeterSerialNo = "GN24A00193",
                            Category = "Single Phase",
                            ConsumerId = 3L,
                            Firmware = "v2.1.5",
                            ICCID = "899110234567890123C",
                            IMSI = "404112345678903",
                            InstallTsUtc = new DateTimeOffset(new DateTime(2024, 4, 1, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IpAddress = "192.168.2.101",
                            Manufacturer = "Genus Power",
                            Status = "Active"
                        },
                        new
                        {
                            MeterSerialNo = "HP24E00301",
                            Category = "Single Phase EV",
                            ConsumerId = 4L,
                            Firmware = "v1.8.0",
                            ICCID = "899110234567890123D",
                            IMSI = "404112345678904",
                            InstallTsUtc = new DateTimeOffset(new DateTime(2024, 6, 5, 9, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IpAddress = "192.168.2.102",
                            Manufacturer = "HPL Electric",
                            Status = "Active"
                        },
                        new
                        {
                            MeterSerialNo = "LT24I00419",
                            Category = "Three Phase CT",
                            ConsumerId = 5L,
                            Firmware = "v5.0.2-beta",
                            ICCID = "899110234567890123E",
                            IMSI = "404112345678905",
                            InstallTsUtc = new DateTimeOffset(new DateTime(2024, 1, 25, 15, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IpAddress = "192.168.1.103",
                            Manufacturer = "L&T Electrical",
                            Status = "Active"
                        },
                        new
                        {
                            MeterSerialNo = "SC23S00078",
                            Category = "Three Phase",
                            Firmware = "v3.3.1",
                            ICCID = "899110234567890123F",
                            IMSI = "404112345678906",
                            InstallTsUtc = new DateTimeOffset(new DateTime(2023, 11, 10, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IpAddress = "10.0.0.10",
                            Manufacturer = "Secure Meters",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Current")
                        .HasColumnType("double precision");

                    b.Property<double>("EnergyConsumed")
                        .HasColumnType("double precision");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PowerFactor")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReadingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("MeterReadings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Current = 5.2000000000000002,
                            EnergyConsumed = 1540.5,
                            MeterId = "GN24A00187",
                            PowerFactor = 0.97999999999999998,
                            ReadingDateTime = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 231.5
                        },
                        new
                        {
                            Id = 2,
                            Current = 5.5,
                            EnergyConsumed = 1715.8,
                            MeterId = "GN24A00187",
                            PowerFactor = 0.98999999999999999,
                            ReadingDateTime = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 229.80000000000001
                        },
                        new
                        {
                            Id = 3,
                            Current = 5.2999999999999998,
                            EnergyConsumed = 1898.2,
                            MeterId = "GN24A00187",
                            PowerFactor = 0.97999999999999998,
                            ReadingDateTime = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 230.09999999999999
                        },
                        new
                        {
                            Id = 4,
                            Current = 15.800000000000001,
                            EnergyConsumed = 8550.2000000000007,
                            MeterId = "LT24C00255",
                            PowerFactor = 0.94999999999999996,
                            ReadingDateTime = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 235.19999999999999
                        },
                        new
                        {
                            Id = 5,
                            Current = 16.100000000000001,
                            EnergyConsumed = 9460.7000000000007,
                            MeterId = "LT24C00255",
                            PowerFactor = 0.95999999999999996,
                            ReadingDateTime = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 234.90000000000001
                        },
                        new
                        {
                            Id = 6,
                            Current = 15.9,
                            EnergyConsumed = 10395.1,
                            MeterId = "LT24C00255",
                            PowerFactor = 0.94999999999999996,
                            ReadingDateTime = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 235.5
                        },
                        new
                        {
                            Id = 7,
                            Current = 6.0999999999999996,
                            EnergyConsumed = 1210.3,
                            MeterId = "GN24A00193",
                            PowerFactor = 0.98999999999999999,
                            ReadingDateTime = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 228.69999999999999
                        },
                        new
                        {
                            Id = 8,
                            Current = 6.4000000000000004,
                            EnergyConsumed = 1435.5,
                            MeterId = "GN24A00193",
                            PowerFactor = 0.98999999999999999,
                            ReadingDateTime = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 229.09999999999999
                        },
                        new
                        {
                            Id = 9,
                            Current = 6.2000000000000002,
                            EnergyConsumed = 1655.9000000000001,
                            MeterId = "GN24A00193",
                            PowerFactor = 0.97999999999999998,
                            ReadingDateTime = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 228.90000000000001
                        },
                        new
                        {
                            Id = 10,
                            Current = 4.5,
                            EnergyConsumed = 525.60000000000002,
                            MeterId = "HP24E00301",
                            PowerFactor = 0.98999999999999999,
                            ReadingDateTime = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 230.5
                        },
                        new
                        {
                            Id = 11,
                            Current = 4.7999999999999998,
                            EnergyConsumed = 680.10000000000002,
                            MeterId = "HP24E00301",
                            PowerFactor = 0.98999999999999999,
                            ReadingDateTime = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 231.19999999999999
                        },
                        new
                        {
                            Id = 12,
                            Current = 4.5999999999999996,
                            EnergyConsumed = 840.29999999999995,
                            MeterId = "HP24E00301",
                            PowerFactor = 0.98999999999999999,
                            ReadingDateTime = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 230.80000000000001
                        },
                        new
                        {
                            Id = 13,
                            Current = 55.200000000000003,
                            EnergyConsumed = 156234.79999999999,
                            MeterId = "LT24I00419",
                            PowerFactor = 0.92000000000000004,
                            ReadingDateTime = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 414.5
                        },
                        new
                        {
                            Id = 14,
                            Current = 58.100000000000001,
                            EnergyConsumed = 168456.10000000001,
                            MeterId = "LT24I00419",
                            PowerFactor = 0.93000000000000005,
                            ReadingDateTime = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 415.10000000000002
                        },
                        new
                        {
                            Id = 15,
                            Current = 56.5,
                            EnergyConsumed = 181050.39999999999,
                            MeterId = "LT24I00419",
                            PowerFactor = 0.92000000000000004,
                            ReadingDateTime = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Voltage = 413.89999999999998
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.OrgUnit", b =>
                {
                    b.Property<int>("OrgUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrgUnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrgUnitId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Type");

                    b.ToTable("OrgUnits", t =>
                        {
                            t.HasCheckConstraint("CK_Type", "\"Type\" IN ('Zone','Substation','Feeder','DTR')");
                        });

                    b.HasData(
                        new
                        {
                            OrgUnitId = 1,
                            Name = "North Zone",
                            Type = "Zone"
                        },
                        new
                        {
                            OrgUnitId = 2,
                            Name = "Maplewood Substation",
                            ParentId = 1,
                            Type = "Substation"
                        },
                        new
                        {
                            OrgUnitId = 3,
                            Name = "Feeder F-11",
                            ParentId = 2,
                            Type = "Feeder"
                        },
                        new
                        {
                            OrgUnitId = 4,
                            Name = "Feeder F-12",
                            ParentId = 2,
                            Type = "Feeder"
                        },
                        new
                        {
                            OrgUnitId = 5,
                            Name = "DTR-11045",
                            ParentId = 3,
                            Type = "DTR"
                        },
                        new
                        {
                            OrgUnitId = 6,
                            Name = "DTR-12001",
                            ParentId = 4,
                            Type = "DTR"
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TariffId"));

                    b.Property<double>("BaseRate")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TaxRate")
                        .HasColumnType("double precision");

                    b.HasKey("TariffId");

                    b.ToTable("Tariffs", t =>
                        {
                            t.HasCheckConstraint("CK_Tariff_BaseRate", "\"BaseRate\" > 0");

                            t.HasCheckConstraint("CK_Tariff_Dates", "\"EffectiveTo\" IS NULL OR \"EffectiveFrom\" < \"EffectiveTo\"");
                        });

                    b.HasData(
                        new
                        {
                            TariffId = 1,
                            BaseRate = 90.0,
                            EffectiveFrom = new DateOnly(2024, 1, 1),
                            Name = "Residential Basic",
                            TaxRate = 0.10000000000000001
                        },
                        new
                        {
                            TariffId = 2,
                            BaseRate = 150.0,
                            EffectiveFrom = new DateOnly(2024, 1, 1),
                            Name = "Commercial Standard",
                            TaxRate = 0.12
                        },
                        new
                        {
                            TariffId = 3,
                            BaseRate = 700.0,
                            EffectiveFrom = new DateOnly(2024, 1, 1),
                            Name = "Industrial High-Load",
                            TaxRate = 0.14999999999999999
                        },
                        new
                        {
                            TariffId = 4,
                            BaseRate = 60.0,
                            EffectiveFrom = new DateOnly(2024, 1, 1),
                            Name = "Agricultural Subsidized",
                            TaxRate = 0.050000000000000003
                        },
                        new
                        {
                            TariffId = 5,
                            BaseRate = 120.0,
                            EffectiveFrom = new DateOnly(2024, 6, 1),
                            Name = "EV Charging Tariff",
                            TaxRate = 0.080000000000000002
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffDetails", b =>
                {
                    b.Property<int>("TariffDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TariffDetailsId"));

                    b.Property<int?>("TariffSlabId")
                        .HasColumnType("integer");

                    b.Property<int?>("TodRuleId")
                        .HasColumnType("integer");

                    b.HasKey("TariffDetailsId");

                    b.HasIndex("TariffSlabId");

                    b.HasIndex("TodRuleId");

                    b.ToTable("TariffDetails");

                    b.HasData(
                        new
                        {
                            TariffDetailsId = 1,
                            TariffSlabId = 1
                        },
                        new
                        {
                            TariffDetailsId = 2,
                            TariffSlabId = 2
                        },
                        new
                        {
                            TariffDetailsId = 3,
                            TariffSlabId = 3
                        },
                        new
                        {
                            TariffDetailsId = 4,
                            TariffSlabId = 4
                        },
                        new
                        {
                            TariffDetailsId = 5,
                            TariffSlabId = 5
                        },
                        new
                        {
                            TariffDetailsId = 6,
                            TariffSlabId = 6
                        },
                        new
                        {
                            TariffDetailsId = 7,
                            TariffSlabId = 7
                        },
                        new
                        {
                            TariffDetailsId = 8,
                            TariffSlabId = 8
                        },
                        new
                        {
                            TariffDetailsId = 9,
                            TariffSlabId = 9
                        },
                        new
                        {
                            TariffDetailsId = 10,
                            TariffSlabId = 10
                        },
                        new
                        {
                            TariffDetailsId = 11,
                            TariffSlabId = 11
                        },
                        new
                        {
                            TariffDetailsId = 12,
                            TariffSlabId = 12
                        },
                        new
                        {
                            TariffDetailsId = 13,
                            TodRuleId = 1
                        },
                        new
                        {
                            TariffDetailsId = 14,
                            TodRuleId = 2
                        },
                        new
                        {
                            TariffDetailsId = 15,
                            TodRuleId = 3
                        },
                        new
                        {
                            TariffDetailsId = 16,
                            TodRuleId = 4
                        },
                        new
                        {
                            TariffDetailsId = 17,
                            TodRuleId = 5
                        },
                        new
                        {
                            TariffDetailsId = 18,
                            TodRuleId = 6
                        },
                        new
                        {
                            TariffDetailsId = 19,
                            TodRuleId = 7
                        },
                        new
                        {
                            TariffDetailsId = 20,
                            TodRuleId = 8
                        },
                        new
                        {
                            TariffDetailsId = 21,
                            TodRuleId = 9
                        },
                        new
                        {
                            TariffDetailsId = 22,
                            TodRuleId = 10
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffSlab", b =>
                {
                    b.Property<int>("TariffSlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TariffSlabId"));

                    b.Property<double>("FromKwh")
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("RatePerKwh")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.Property<double>("ToKwh")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("TariffSlabId");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffSlabs", t =>
                        {
                            t.HasCheckConstraint("CK_TariffSlab_Range", "\"FromKwh\" >= 0 AND \"ToKwh\" > \"FromKwh\"");

                            t.HasCheckConstraint("CK_TariffSlab_Rate", "\"RatePerKwh\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            TariffSlabId = 1,
                            FromKwh = 0.0,
                            IsDeleted = false,
                            RatePerKwh = 4.5,
                            TariffId = 1,
                            ToKwh = 100.0
                        },
                        new
                        {
                            TariffSlabId = 2,
                            FromKwh = 100.000001,
                            IsDeleted = false,
                            RatePerKwh = 6.0,
                            TariffId = 1,
                            ToKwh = 200.0
                        },
                        new
                        {
                            TariffSlabId = 3,
                            FromKwh = 200.000001,
                            IsDeleted = false,
                            RatePerKwh = 8.5,
                            TariffId = 1,
                            ToKwh = 500.0
                        },
                        new
                        {
                            TariffSlabId = 4,
                            FromKwh = 0.0,
                            IsDeleted = false,
                            RatePerKwh = 7.0,
                            TariffId = 2,
                            ToKwh = 500.0
                        },
                        new
                        {
                            TariffSlabId = 5,
                            FromKwh = 500.000001,
                            IsDeleted = false,
                            RatePerKwh = 9.25,
                            TariffId = 2,
                            ToKwh = 1000.0
                        },
                        new
                        {
                            TariffSlabId = 6,
                            FromKwh = 1000.000001,
                            IsDeleted = false,
                            RatePerKwh = 11.0,
                            TariffId = 2,
                            ToKwh = 5000.0
                        },
                        new
                        {
                            TariffSlabId = 7,
                            FromKwh = 0.0,
                            IsDeleted = false,
                            RatePerKwh = 9.5,
                            TariffId = 3,
                            ToKwh = 10000.0
                        },
                        new
                        {
                            TariffSlabId = 8,
                            FromKwh = 10000.000001,
                            IsDeleted = false,
                            RatePerKwh = 12.0,
                            TariffId = 3,
                            ToKwh = 100000.0
                        },
                        new
                        {
                            TariffSlabId = 9,
                            FromKwh = 0.0,
                            IsDeleted = false,
                            RatePerKwh = 2.5,
                            TariffId = 4,
                            ToKwh = 300.0
                        },
                        new
                        {
                            TariffSlabId = 10,
                            FromKwh = 300.000001,
                            IsDeleted = false,
                            RatePerKwh = 3.5,
                            TariffId = 4,
                            ToKwh = 1000.0
                        },
                        new
                        {
                            TariffSlabId = 11,
                            FromKwh = 0.0,
                            IsDeleted = false,
                            RatePerKwh = 5.75,
                            TariffId = 5,
                            ToKwh = 50.0
                        },
                        new
                        {
                            TariffSlabId = 12,
                            FromKwh = 50.000000999999997,
                            IsDeleted = false,
                            RatePerKwh = 6.5,
                            TariffId = 5,
                            ToKwh = 200.0
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TodRule", b =>
                {
                    b.Property<int>("TodRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TodRuleId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RatePerKwh")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer");

                    b.HasKey("TodRuleId");

                    b.HasIndex("Name");

                    b.HasIndex("TariffId");

                    b.ToTable("TodRules", t =>
                        {
                            t.HasCheckConstraint("CK_TodRule_Rate", "\"RatePerKwh\" > 0");

                            t.HasCheckConstraint("CK_TodRule_Time", "\"EndTime\" > \"StartTime\"");
                        });

                    b.HasData(
                        new
                        {
                            TodRuleId = 1,
                            EndTime = new TimeOnly(22, 0, 0),
                            IsDeleted = false,
                            Name = "Peak Hours",
                            RatePerKwh = 10.5,
                            StartTime = new TimeOnly(18, 0, 0),
                            TariffId = 2
                        },
                        new
                        {
                            TodRuleId = 2,
                            EndTime = new TimeOnly(23, 59, 59),
                            IsDeleted = false,
                            Name = "Off-Peak Hours (Evening)",
                            RatePerKwh = 5.5,
                            StartTime = new TimeOnly(22, 0, 0),
                            TariffId = 2
                        },
                        new
                        {
                            TodRuleId = 8,
                            EndTime = new TimeOnly(6, 0, 0),
                            IsDeleted = false,
                            Name = "Off-Peak Hours (Morning)",
                            RatePerKwh = 5.5,
                            StartTime = new TimeOnly(0, 0, 0),
                            TariffId = 2
                        },
                        new
                        {
                            TodRuleId = 3,
                            EndTime = new TimeOnly(18, 0, 0),
                            IsDeleted = false,
                            Name = "Standard Hours",
                            RatePerKwh = 7.5,
                            StartTime = new TimeOnly(6, 0, 0),
                            TariffId = 2
                        },
                        new
                        {
                            TodRuleId = 4,
                            EndTime = new TimeOnly(23, 0, 0),
                            IsDeleted = false,
                            Name = "Industrial Peak",
                            RatePerKwh = 13.0,
                            StartTime = new TimeOnly(17, 0, 0),
                            TariffId = 3
                        },
                        new
                        {
                            TodRuleId = 5,
                            EndTime = new TimeOnly(23, 59, 59),
                            IsDeleted = false,
                            Name = "Industrial Off-Peak (Evening)",
                            RatePerKwh = 7.0,
                            StartTime = new TimeOnly(23, 0, 0),
                            TariffId = 3
                        },
                        new
                        {
                            TodRuleId = 9,
                            EndTime = new TimeOnly(5, 0, 0),
                            IsDeleted = false,
                            Name = "Industrial Off-Peak (Morning)",
                            RatePerKwh = 7.0,
                            StartTime = new TimeOnly(0, 0, 0),
                            TariffId = 3
                        },
                        new
                        {
                            TodRuleId = 6,
                            EndTime = new TimeOnly(23, 59, 59),
                            IsDeleted = false,
                            Name = "EV Super Off-Peak (Evening)",
                            RatePerKwh = 4.5,
                            StartTime = new TimeOnly(23, 0, 0),
                            TariffId = 5
                        },
                        new
                        {
                            TodRuleId = 10,
                            EndTime = new TimeOnly(5, 0, 0),
                            IsDeleted = false,
                            Name = "EV Super Off-Peak (Morning)",
                            RatePerKwh = 4.5,
                            StartTime = new TimeOnly(0, 0, 0),
                            TariffId = 5
                        },
                        new
                        {
                            TodRuleId = 7,
                            EndTime = new TimeOnly(22, 0, 0),
                            IsDeleted = false,
                            Name = "EV Peak",
                            RatePerKwh = 8.0,
                            StartTime = new TimeOnly(19, 0, 0),
                            TariffId = 5
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LoginLockEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            DisplayName = "System Administrator",
                            Email = "admin@smartmeter.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            PasswordHash = "$2a$11$nG48 / pPMTnCvehLK.ebbXeEXvw5XqJwPLkHPsH5Cuc2466gvIrP8C",
                            Phone = "9876543210",
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 2L,
                            DisplayName = "Ganesh",
                            Email = "ganesh@smartmeter.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            PasswordHash = "$2a$11$nlUMkcxzYytmlcZWNuDQ0enFXhKDKD9gAHtr45pHlKA.eaPJ9Vi/.",
                            Phone = "9123456780",
                            UserName = "ganesh"
                        },
                        new
                        {
                            UserId = 3L,
                            DisplayName = "Support Engineer",
                            Email = "support1@smartmeter.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            PasswordHash = "$2a$11$6EK8mbMOJbJLh0adk1hiQeWeij8lW3OeEeOHyB4/aRRp4Tv1nxCfS",
                            Phone = "9998887770",
                            UserName = "support1"
                        },
                        new
                        {
                            UserId = 4L,
                            DisplayName = "Energy Auditor",
                            Email = "auditor@smartmeter.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            PasswordHash = "$2a$11$U1yXqZUuWV3AoF8Nv78NlePvk7.65UckxVZQ3Nn3qoSdtjpkL9Nn6",
                            Phone = "9988776655",
                            UserName = "auditor"
                        },
                        new
                        {
                            UserId = 5L,
                            DisplayName = "Viewer Account",
                            Email = "viewer@smartmeter.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            PasswordHash = "$2a$11$4A4WI6j0RrYKDbl6ZAmhze6JNH..fZL98NexIsYTAR/Jk9JtFoZv6",
                            Phone = "9876501234",
                            UserName = "viewer"
                        });
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Address", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Arrear", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Billing", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Consumer", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeterWeb.Data.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgUnit");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.Meter", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Consumer", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.MeterReading", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.OrgUnit", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.OrgUnit", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffDetails", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.TariffSlab", "TariffSlab")
                        .WithMany()
                        .HasForeignKey("TariffSlabId");

                    b.HasOne("SmartMeterWeb.Data.Entities.TodRule", "TodRule")
                        .WithMany()
                        .HasForeignKey("TodRuleId");

                    b.Navigation("TariffSlab");

                    b.Navigation("TodRule");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TariffSlab", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("SmartMeterWeb.Data.Entities.TodRule", b =>
                {
                    b.HasOne("SmartMeterWeb.Data.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });
#pragma warning restore 612, 618
        }
    }
}
